spring.application.name=crudSpringBootDemo

spring.datasource.url = jdbc:postgres://localhost:5432/demo
spring.datasource.username = postgres
spring.datasource.password = AmanAg@8230

spring.jpa.hibernate.ddl-auto=update
